import 'package:flutter_test/flutter_test.dart';
import 'package:smartscanocr/features/documents/data/document_exporter.dart';
import 'package:smartscanocr/features/pdf_export/domain/entities/pdf_export_mode.dart';

import 'support/factories.dart';
import 'support/fakes.dart';

void main() {
  late FakePdfExportService pdf;
  late FakeFileStorageService storage;
  late FakeSharingService sharing;

  DocumentExporter exporter() =>
      DocumentExporter(pdfService: pdf, storage: storage, sharing: sharing);

  setUp(() {
    pdf = FakePdfExportService();
    storage = FakeFileStorageService();
    sharing = FakeSharingService();
  });

  test(
    'export with watermark shares the stored PDF under the title name',
    () async {
      final doc = makeDocument(id: '1', title: 'March Invoice', text: 'x');
      final outcome = await exporter().exportWithWatermark(doc);

      expect(outcome.kind, ExportOutcomeKind.shared);
      expect(pdf.renderModes, isEmpty, reason: 'reuses the stored export.pdf');
      expect(sharing.sharedPdfNames.single, 'March_Invoice.pdf');
    },
  );

  test(
    'watermark-free export renders a watermark-free temp; export.pdf untouched',
    () async {
      final doc = makeDocument(id: '1', title: 'March Invoice', text: 'x');
      final outcome = await exporter().exportWatermarkFree(doc);

      expect(outcome.kind, ExportOutcomeKind.shared);
      expect(pdf.renderModes, [PdfExportMode.watermarkFree]);
      expect(storage.tempShareBytes.keys.single, 'March_Invoice.pdf');
      expect(
        storage.committedPdfBytes,
        isNull,
        reason: 'stored export.pdf is never regenerated by an export',
      );
      expect(sharing.sharedPdfNames.single, 'March_Invoice.pdf');
    },
  );

  test(
    'export with watermark on a doc without a PDF returns an error',
    () async {
      final doc = makeDocument(id: '1', title: 'X', text: 'x', pdfPath: null);
      final outcome = await exporter().exportWithWatermark(doc);
      expect(outcome.kind, ExportOutcomeKind.error);
      expect(sharing.sharedPdfPaths, isEmpty);
    },
  );
}
